version: '3'

services:
  ganache:
    image: trufflesuite/ganache:v7.9.2
    container_name: ganache
    ports:
      - '8545:8545'
    command: ["-h", "0.0.0.0", "-m", "rifle cloud amused end pyramid swarm anxiety kitchen ceiling cotton rib gain"]
  
  ganache_wait:
    image: alpine
    command:
      - /bin/sh
      - -c
      - |
          echo "sleep for 10sec"
          sleep 10 
    depends_on:
      - ganache

  deploy_intentoperatorsregistry:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: deploy_intentoperatorsregistry
    command: ["--privateKey", "76163f58a83febacfdef93e2142591d4d676432fa6c737ce1dd90a51083c461a", "--rpcURL", "http://ganache:8545", "--isDeployIntentOperatorsRegistry", "true"]
    depends_on:
      ganache_wait:
          condition: service_completed_successfully

  deploy_solversregistry:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: deploy_solversregistry
    command: ["--privateKey", "76163f58a83febacfdef93e2142591d4d676432fa6c737ce1dd90a51083c461a", "--rpcURL", "http://ganache:8545", "--isDeploySolversRegistry", "true"]
    depends_on:
      deploy_intentoperatorsregistry:
          condition: service_completed_successfully

  deploy_bridge:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: deploy_bridge
    command: ["--privateKey", "76163f58a83febacfdef93e2142591d4d676432fa6c737ce1dd90a51083c461a", "--rpcURL", "http://ganache:8545", "--isDeployBridge", "true"]
    depends_on:
      deploy_solversregistry:
          condition: service_completed_successfully

  deploy_eth_token:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: deploy_eth_token
    command: ["--privateKey", "76163f58a83febacfdef93e2142591d4d676432fa6c737ce1dd90a51083c461a", "--rpcURL", "http://ganache:8545", "--isDeployBridgeToken", "true", "--tokenName", "Strip ETH", "--tokenSymbol", "sETH", "--tokenDecimals", "18"]
    depends_on:
      deploy_bridge:
          condition: service_completed_successfully

  deploy_sol_token:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: deploy_sol_token
    command: ["--privateKey", "76163f58a83febacfdef93e2142591d4d676432fa6c737ce1dd90a51083c461a", "--rpcURL", "http://ganache:8545", "--isDeployBridgeToken", "true", "--tokenName", "Strip SOL", "--tokenSymbol", "sSOL", "--tokenDecimals", "9"]
    depends_on:
      deploy_eth_token:
          condition: service_completed_successfully

  deploy_usdc_token:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: deploy_usdc_token
    command: ["--privateKey", "76163f58a83febacfdef93e2142591d4d676432fa6c737ce1dd90a51083c461a", "--rpcURL", "http://ganache:8545", "--isDeployBridgeToken", "true", "--tokenName", "Strip USDC", "--tokenSymbol", "sUSDC", "--tokenDecimals", "6"]
    depends_on:
      deploy_sol_token:
          condition: service_completed_successfully
  
  deploy_original_usdc_token:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: deploy_original_usdc_token
    command: ["--privateKey", "76163f58a83febacfdef93e2142591d4d676432fa6c737ce1dd90a51083c461a", "--rpcURL", "http://ganache:8545", "--isDeployERC20Token", "true", "--tokenName", "USD Coin", "--tokenSymbol", "USDC", "--tokenDecimals", "6"]
    depends_on:
      deploy_usdc_token:
          condition: service_completed_successfully

  add_eth_pegged_token:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: deploy_eth_pegged_token
    command: ["--privateKey", "76163f58a83febacfdef93e2142591d4d676432fa6c737ce1dd90a51083c461a", "--rpcURL", "http://ganache:8545", "--chainId", "1337","--tokenAddress", "0x0000000000000000000000000000000000000000", "--peggedToken", "0x37AA3eF8aB0CD9E22D4Cfce5355ec2cd07e9E36B","--isAddToken", "true",  ]
    depends_on:
      deploy_original_usdc_token:
          condition: service_completed_successfully

  add_usdc_pegged_token:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: add_usdc_pegged_token
    command: ["--privateKey", "76163f58a83febacfdef93e2142591d4d676432fa6c737ce1dd90a51083c461a", "--rpcURL", "http://ganache:8545", "--chainId", "1337","--tokenAddress", "0x0c3729964A75870f9c692833A18AFE315be700e1", "--peggedToken", "0x9af0e87FBA28e20863488bda3CfA012d1c7863d9","--isAddToken", "true",  ]
    depends_on:
      add_eth_pegged_token:
          condition: service_completed_successfully
  
  add_sol_pegged_token:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: deploy_sol_pegged_token
    command: ["--privateKey", "76163f58a83febacfdef93e2142591d4d676432fa6c737ce1dd90a51083c461a", "--rpcURL", "http://ganache:8545",  "--chainId", "901","--tokenAddress", "0x0000000000000000000000000000000000000000", "--peggedToken", "0x45ff1aD4D8BdDC5c9573f8e30f725D3FF12A0a3e","--isAddToken", "true"]
    depends_on:
      add_usdc_pegged_token:
          condition: service_completed_successfully

  deploy-dex:
    image: strip-contracts
    container_name: deploy-dex
    depends_on:
      add_sol_pegged_token:
        condition: service_completed_successfully

  add_signer_1:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: add_signer_1
    command: ["--privateKey", "76163f58a83febacfdef93e2142591d4d676432fa6c737ce1dd90a51083c461a", "--rpcURL", "http://ganache:8545", "--signerNodeURL", "http://signer1:8080", "--signerPublicKey", "0x26d1556a83c01a9d2b1cce29b32cb520238efc602f86481d2d0b9af8a2fff0cf", "--isAddsigner", "true"]
    depends_on:
      deploy-dex:
        condition: service_completed_successfully

  add_signer_2:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: add_signer_2
    command: ["--privateKey", "76163f58a83febacfdef93e2142591d4d676432fa6c737ce1dd90a51083c461a", "--rpcURL", "http://ganache:8545", "--signerNodeURL", "http://signer2:8080", "--signerPublicKey", "0x54455a1f7f4244ef645ac62baa8bd90af0cc18cdb0eae369766b7b58134edf35", "--isAddsigner", "true"]
    depends_on:
      add_signer_1:
        condition: service_completed_successfully
  
  add_solver:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: add_solver
    command: ["--privateKey", "76163f58a83febacfdef93e2142591d4d676432fa6c737ce1dd90a51083c461a", "--rpcURL", "http://ganache:8545", "--solverDomain", "http://solver:8083", "--isAddSolver", "true"]
    depends_on:
      add_signer_2:
        condition: service_completed_successfully

  bootnode:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: bootnode
    ports:
      - '30303:30303'
    command: ["--port", "30303", "--keyPath", "/app/static-bootnode", "--isBootstrap", "true"]
    depends_on:
      add_solver:
        condition: service_completed_successfully

  signer1postgres:
    image: postgres:14.13
    container_name: signer1postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
  
  signer2postgres:
    image: postgres:14.13
    container_name: signer2postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5433:5432'

  signer1:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: signer1
    depends_on:
      - bootnode
      - signer1postgres
    ports:
      - '30304:30304'
      - '8080:8080'
    command: ["--signerPublicKey", "0x26d1556a83c01a9d2b1cce29b32cb520238efc602f86481d2d0b9af8a2fff0cf", "--signerPrivateKey", "0xb0a0aa1369839ffbf2778fcedcad2ba70b0237e6071b791a80a6f9e11380ffa2", "--rpcURL", "http://ganache:8545", "--httpPort", "8080", "--port", "30304", "--postgresHost", "signer1postgres:5432", "--bootnode", "/dns/bootnode/tcp/30303/p2p/QmTfM73oQxzx6DVyjCm5AECW3hVbXJiSLYtosNauaX9gJR"]

  signer2:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: signer2
    depends_on:
      - bootnode
      - signer2postgres
    ports:
      - '30305:30305'
      - '8081:8081'
    command: ["--signerPublicKey", "0x54455a1f7f4244ef645ac62baa8bd90af0cc18cdb0eae369766b7b58134edf35", "--signerPrivateKey", "0x4d539b1896a8f7064a7207fa005b13b64f90eff78564e278c14b1089d2d5f8de", "--rpcURL", "http://ganache:8545", "--httpPort", "8081", "--port", "30305", "--postgresHost", "signer2postgres:5432", "--bootnode", "/dns/bootnode/tcp/30303/p2p/QmTfM73oQxzx6DVyjCm5AECW3hVbXJiSLYtosNauaX9gJR"]

  sequencerpostgres:
    image: postgres:14.13
    container_name: sequencerpostgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5434:5432'

  set_swap_router:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: set_swap_router
    command: ["--privateKey", "76163f58a83febacfdef93e2142591d4d676432fa6c737ce1dd90a51083c461a", "--rpcURL", "http://ganache:8545", "--isSetSwapRouter", "true"]
    depends_on:
      - signer2
      - signer1

  sequencer_wait:
    image: alpine
    depends_on:
      - set_swap_router
    command:
      - /bin/sh
      - -c
      - |
          echo "sleep for 60sec"
          sleep 60 

  sequencer:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: sequencer
    environment:
      CLIENT_ID: 172185463433-hrhcoosjhiti0bujtmma2h666mdjcb23.apps.googleusercontent.com
      CLIENT_SECRET: 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
      JWT_SECRET: "5b40a9b6f8ea8fba40c6eed87b5fadf4558c9a2f19e6048dd4cf2c4f9a63e6f748709e2a617333f09a548f60f5ce78d636cd8d89af444884d19e0353a7956abc7a4e8901fe189e627bd6a7c2becb29d6e722cce4cae5ce53280c57efbf0746e50a3290a61355f7345b93d7ff995a93406c3b1052a058d9655a8c974be1a64db8d73a55730b1858d4a29ca712374ff09c2b8e153f4a7e3e479748a87115db148a2c1292715d2a850ea28a10b2a28d4f4f96cdca43cf4499eaed745f4ac8087a1a9a233e207862da7b21e13125387d33daf15cf55a988643b87ce3f59ce02dd707254786746094d3fb3ead257f450a2c9ae3d9dcc01d49e5d778e37f3ccda0c437"
      SESSION_SECRET: "RGKMaUIbA62yjNxT4jQt24nyuKE9hne8oEdZNq26miYnWl7Zwr5sqTE8SYQduXB"
    depends_on:
      sequencer_wait:
        condition: service_completed_successfully
    ports:
      - '30306:30306'
      - '80:8082'
    command: ["--privateKey", "76163f58a83febacfdef93e2142591d4d676432fa6c737ce1dd90a51083c461a", "--rpcURL", "http://ganache:8545", "--httpPort", "8082", "--postgresHost", "sequencerpostgres:5432", "--redirectUrl", "http://localhost:8082/oauth/callback", "--enableOAuth", "--isSequencer", "true"]
  
  solver:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: solver
    ports:
      - '8083:8083'
    command: ["--httpPort", "8083", "--isTestSolver", "true"]