version: '3'

services:
  ganache:
    image: trufflesuite/ganache:v7.9.2
    container_name: ganache
    ports:
      - '8545:8545'
    command: ["-h", "0.0.0.0", "-m", "rifle cloud amused end pyramid swarm anxiety kitchen ceiling cotton rib gain"]

  deploy_intentoperatorsregistry:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: deploy_intentoperatorsregistry
    command: ["--privateKey", "76163f58a83febacfdef93e2142591d4d676432fa6c737ce1dd90a51083c461a", "--rpcURL", "http://ganache:8545", "--isDeployIntentOperatorsRegistry", "true"]
    depends_on:
      - ganache

  add_signer_1:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: add_signer_1
    command: ["--privateKey", "76163f58a83febacfdef93e2142591d4d676432fa6c737ce1dd90a51083c461a", "--rpcURL", "http://ganache:8545", "--signerNodeURL", "http://signer1:8080", "--signerPublicKey", "0x26d1556a83c01a9d2b1cce29b32cb520238efc602f86481d2d0b9af8a2fff0cf", "--isAddsigner", "true"]
    depends_on:
      deploy_intentoperatorsregistry:
        condition: service_completed_successfully

  add_signer_2:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: add_signer_2
    command: ["--privateKey", "76163f58a83febacfdef93e2142591d4d676432fa6c737ce1dd90a51083c461a", "--rpcURL", "http://ganache:8545", "--signerNodeURL", "http://signer2:8080", "--signerPublicKey", "0x54455a1f7f4244ef645ac62baa8bd90af0cc18cdb0eae369766b7b58134edf35", "--isAddsigner", "true"]
    depends_on:
      add_signer_1:
        condition: service_completed_successfully

  bootnode:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: bootnode
    ports:
      - '30303:30303'
    command: ["--port", "30303", "--keyPath", "/app/static-bootnode", "--isBootstrap", "true"]
    depends_on:
      add_signer_2:
        condition: service_completed_successfully

  signer1postgres:
    image: postgres:latest
    container_name: signer1postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
  
  signer2postgres:
    image: postgres:latest
    container_name: signer2postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5433:5432'

  signer1:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: signer1
    depends_on:
      - bootnode
      - signer1postgres
    ports:
      - '30304:30304'
      - '8080:8080'
    command: ["--signerPublicKey", "0x26d1556a83c01a9d2b1cce29b32cb520238efc602f86481d2d0b9af8a2fff0cf", "--signerPrivateKey", "0xb0a0aa1369839ffbf2778fcedcad2ba70b0237e6071b791a80a6f9e11380ffa2", "--rpcURL", "http://ganache:8545", "--httpPort", "8080", "--port", "30304", "--postgresHost", "signer1postgres:5432", "--bootnode", "/dns/bootnode/tcp/30303/p2p/QmTfM73oQxzx6DVyjCm5AECW3hVbXJiSLYtosNauaX9gJR"]

  signer2:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: signer2
    depends_on:
      - bootnode
      - signer2postgres
    ports:
      - '30305:30305'
      - '8081:8081'
    command: ["--signerPublicKey", "0x54455a1f7f4244ef645ac62baa8bd90af0cc18cdb0eae369766b7b58134edf35", "--signerPrivateKey", "0x4d539b1896a8f7064a7207fa005b13b64f90eff78564e278c14b1089d2d5f8de", "--rpcURL", "http://ganache:8545", "--httpPort", "8081", "--port", "30305", "--postgresHost", "signer2postgres:5432", "--bootnode", "/dns/bootnode/tcp/30303/p2p/QmTfM73oQxzx6DVyjCm5AECW3hVbXJiSLYtosNauaX9gJR"]

  sequencerpostgres:
    image: postgres:latest
    container_name: sequencerpostgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5434:5432'

  sequencer:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: sequencer
    depends_on:
      - signer2
      - signer1
    ports:
      - '30306:30306'
      - '8082:8082'
    command: ["--rpcURL", "http://ganache:8545", "--httpPort", "8082", "--postgresHost", "sequencerpostgres:5432", "--isSequencer", "true"]