version: '3'

services:
  ganache:
    image: trufflesuite/ganache:v7.7.7
    container_name: ganache
    ports:
      - '8545:8545'
    command: ["-h", "0.0.0.0", "-m", "rifle cloud amused end pyramid swarm anxiety kitchen ceiling cotton rib gain"]

  deploy_signerhub:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: deploy_signerhub
    command: ["--privateKey", "76163f58a83febacfdef93e2142591d4d676432fa6c737ce1dd90a51083c461a", "--rpcURLs", "http://ganache:8545", "--isDeploySignerHub", "true", "--networkIds", "1337"]
    depends_on:
      - ganache

  add_signer_1:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: add_signer_1
    command: ["--privateKey", "76163f58a83febacfdef93e2142591d4d676432fa6c737ce1dd90a51083c461a", "--rpcURLs", "http://ganache:8545", "--signerPublicKey", "0x0226d1556a83c01a9d2b1cce29b32cb520238efc602f86481d2d0b9af8a2fff0cf", "--isAddsigner", "true", "--networkIds", "1337"]
    depends_on:
      deploy_paymaster:
        condition: service_completed_successfully

  add_signer_2:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: add_signer_2
    command: ["--privateKey", "76163f58a83febacfdef93e2142591d4d676432fa6c737ce1dd90a51083c461a", "--rpcURLs", "http://ganache:8545", "--signerPublicKey", "0x0354455a1f7f4244ef645ac62baa8bd90af0cc18cdb0eae369766b7b58134edf35", "--isAddsigner", "true", "--networkIds", "1337"]
    depends_on:
      add_signer_1:
        condition: service_completed_successfully


  bootnode:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: bootnode
    ports:
      - '30303:30303'
    command: ["--port", "30303", "--keyPath", "/app/static-bootnode", "--isBootstrap", "true"]
    depends_on:
      add_signer_2:
        condition: service_completed_successfully

  signer1:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: signer1
    depends_on:
      - bootnode
    ports:
      - '30304:30304'
      - '8080:8080'
    command: ["--signerPublicKey", "0x0226d1556a83c01a9d2b1cce29b32cb520238efc602f86481d2d0b9af8a2fff0cf", "--signerPrivateKey", "0xb0a0aa1369839ffbf2778fcedcad2ba70b0237e6071b791a80a6f9e11380ffa2", "--rpcURLs", "http://ganache:8545", "--keyPath", "/app/keys", "--httpPort", "8080", "--port", "30304", "--bootnode", "/dns/bootnode/tcp/30303/p2p/QmTfM73oQxzx6DVyjCm5AECW3hVbXJiSLYtosNauaX9gJR", "--privateKey", "76163f58a83febacfdef93e2142591d4d676432fa6c737ce1dd90a51083c461a", "--networkIds", "1337"]
    depends_on:
      add_signer_2:
        condition: service_completed_successfully

  signer2:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: signer2
    depends_on:
      - bootnode
    ports:
      - '30305:30305'
      - '8081:8081'
    command: ["--signerPublicKey", "0x0354455a1f7f4244ef645ac62baa8bd90af0cc18cdb0eae369766b7b58134edf35", "--signerPrivateKey", "0x4d539b1896a8f7064a7207fa005b13b64f90eff78564e278c14b1089d2d5f8de", "--rpcURLs", "http://ganache:8545", "--keyPath", "/app/keys", "--httpPort", "8081", "--port", "30305", "--bootnode", "/dns/bootnode/tcp/30303/p2p/QmTfM73oQxzx6DVyjCm5AECW3hVbXJiSLYtosNauaX9gJR", "--networkIds", "1337"]
    depends_on:
      add_signer_2:
        condition: service_completed_successfully