apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-ingress
  namespace: dev
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:806060079291:certificate/3b1d2a54-ec40-40ee-a98f-e00757f5f4b3
    alb.ingress.kubernetes.io/subnets: subnet-0992c88cfabe19b42, subnet-071c47a540186c254, subnet-0ab041dd89aaa7dd5, subnet-0cc042f2f020fec15, subnet-05845cd9e038906cd
    alb.ingress.kubernetes.io/enable-cors: "true"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=30
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "10"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "6"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "2"
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=60
    alb.ingress.kubernetes.io/group.name: "stripchain"
    alb.ingress.kubernetes.io/group.order: "1"
    alb.ingress.kubernetes.io/conditions.ssl-redirect: '[{"field":"path-pattern", "pathPatternConfig":{"values":["/*"]}}]'
spec:
  ingressClassName: alb
  rules:
  - host: dev-api-tls.stripchain.xyz
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: apis-laststrip
            port:
              number: 80
  - host: solver.stripchain.xyz
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: backend-strip-node-solver
            port:
              number: 80
  - host: sequencer.stripchain.xyz
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: backend-strip-node-sequencer
            port:
              number: 80
  - host: validator1.stripchain.xyz
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: backend-strip-node-validator1
            port:
              number: 80
  - host: validator2.stripchain.xyz
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: backend-strip-node-validator2
            port:
              number: 80
  - host: validator3.stripchain.xyz
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: backend-strip-node-validator3
            port:
              number: 80
  - host: validator4.stripchain.xyz
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: backend-strip-node-validator4
            port:
              number: 80
  - host: validator5.stripchain.xyz
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: backend-strip-node-validator5
            port:
              number: 80
  - host: validator6.stripchain.xyz
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: backend-strip-node-validator6
            port:
              number: 80
  - host: validator7.stripchain.xyz
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: backend-strip-node-validator7
            port:
              number: 80
  - host: validator8.stripchain.xyz
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: backend-strip-node-validator8
            port:
              number: 80