apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-strip-node-sequencer
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-strip-node-sequencer
  template:
    metadata:
      labels:
        app: backend-strip-node-sequencer
    spec:
      initContainers:
        - name: wait-for-signers
          image: busybox
          command: ['sh', '-c', 'until nslookup backend-strip-node-validator1.dev.svc.cluster.local && nslookup backend-strip-node-validator2.dev.svc.cluster.local; do echo waiting for signers; sleep 2; done;']
      containers:
        - name: backend-strip-node-sequencer
          image: 806060079291.dkr.ecr.us-east-1.amazonaws.com/dev/backend/strip-node/sequencer:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1500m"
              memory: "2Gi"
          env:
            - name: ROLE
              value: "sequencer"
            - name: IS_SEQUENCER
              value: "true"
            - name: HTTP_CLIENT_TIMEOUT
              value: "300s"
            - name: KEYGEN_TIMEOUT
              value: "600s"
            - name: PRIVATE_KEY
              value: "76163f58a83febacfdef93e2142591d4d676432fa6c737ce1dd90a51083c461a"
            - name: RPC_URL
              value: "https://rpc-stripsepolia-5w8r5b9f7b.t.conduit.xyz"
            - name: HTTP_PORT
              value: "8080"
            - name: PORT
              value: "30306"
            - name: POSTGRES_HOST
              value: "dev-stage-stripchain.clrdhmz5qrnm.us-east-1.rds.amazonaws.com:5432"
            - name: POSTGRES_PASSWORD
              value: "z2D76R4euvBd"
            - name: POSTGRES_DB
              value: "sequencer"
            - name: POSTGRES_USER
              value: "postgres"
            - name: SIGNER_HUB_CONTRACT_ADDRESS
              value: "0x2001fB1169aC097C2AADE991543dB1A55D7bFd4c"
            - name: SOLVERS_REGISTRY_ADDRESS
              value: "0x77127C2fF8C77bCD8F0461b207fc435d10b86989"
            - name: BRIDGE_CONTRACT_ADDRESS
              value: "0xeEDD625917C74bb5baE72d9E23A1EB776Af247D4"
