// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: libs/proto/validator.proto

package validator

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Curve int32

const (
	Curve_CURVE_UNSPECIFIED Curve = 0
	Curve_CURVE_ECDSA       Curve = 1
	Curve_CURVE_EDDSA       Curve = 2
)

// Enum value maps for Curve.
var (
	Curve_name = map[int32]string{
		0: "CURVE_UNSPECIFIED",
		1: "CURVE_ECDSA",
		2: "CURVE_EDDSA",
	}
	Curve_value = map[string]int32{
		"CURVE_UNSPECIFIED": 0,
		"CURVE_ECDSA":       1,
		"CURVE_EDDSA":       2,
	}
)

func (x Curve) Enum() *Curve {
	p := new(Curve)
	*p = x
	return p
}

func (x Curve) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Curve) Descriptor() protoreflect.EnumDescriptor {
	return file_libs_proto_validator_proto_enumTypes[0].Descriptor()
}

func (Curve) Type() protoreflect.EnumType {
	return &file_libs_proto_validator_proto_enumTypes[0]
}

func (x Curve) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Curve.Descriptor instead.
func (Curve) EnumDescriptor() ([]byte, []int) {
	return file_libs_proto_validator_proto_rawDescGZIP(), []int{0}
}

type BlockchainID int32

const (
	BlockchainID_BLOCKCHAIN_ID_UNSPECIFIED BlockchainID = 0
	BlockchainID_BITCOIN                   BlockchainID = 1
	BlockchainID_ETHEREUM                  BlockchainID = 2
	BlockchainID_SOLANA                    BlockchainID = 3
	BlockchainID_DOGECOIN                  BlockchainID = 4
	BlockchainID_SUI                       BlockchainID = 5
	BlockchainID_APTOS                     BlockchainID = 6
	BlockchainID_STELLAR                   BlockchainID = 7
	BlockchainID_ALGORAND                  BlockchainID = 8
	BlockchainID_RIPPLE                    BlockchainID = 9
	BlockchainID_CARDANO                   BlockchainID = 10
	BlockchainID_STRIPCHAIN                BlockchainID = 11
	BlockchainID_ARBITRUM                  BlockchainID = 12
	BlockchainID_SONIC                     BlockchainID = 13
	BlockchainID_BERACHAIN                 BlockchainID = 14
)

// Enum value maps for BlockchainID.
var (
	BlockchainID_name = map[int32]string{
		0:  "BLOCKCHAIN_ID_UNSPECIFIED",
		1:  "BITCOIN",
		2:  "ETHEREUM",
		3:  "SOLANA",
		4:  "DOGECOIN",
		5:  "SUI",
		6:  "APTOS",
		7:  "STELLAR",
		8:  "ALGORAND",
		9:  "RIPPLE",
		10: "CARDANO",
		11: "STRIPCHAIN",
		12: "ARBITRUM",
		13: "SONIC",
		14: "BERACHAIN",
	}
	BlockchainID_value = map[string]int32{
		"BLOCKCHAIN_ID_UNSPECIFIED": 0,
		"BITCOIN":                   1,
		"ETHEREUM":                  2,
		"SOLANA":                    3,
		"DOGECOIN":                  4,
		"SUI":                       5,
		"APTOS":                     6,
		"STELLAR":                   7,
		"ALGORAND":                  8,
		"RIPPLE":                    9,
		"CARDANO":                   10,
		"STRIPCHAIN":                11,
		"ARBITRUM":                  12,
		"SONIC":                     13,
		"BERACHAIN":                 14,
	}
)

func (x BlockchainID) Enum() *BlockchainID {
	p := new(BlockchainID)
	*p = x
	return p
}

func (x BlockchainID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BlockchainID) Descriptor() protoreflect.EnumDescriptor {
	return file_libs_proto_validator_proto_enumTypes[1].Descriptor()
}

func (BlockchainID) Type() protoreflect.EnumType {
	return &file_libs_proto_validator_proto_enumTypes[1]
}

func (x BlockchainID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BlockchainID.Descriptor instead.
func (BlockchainID) EnumDescriptor() ([]byte, []int) {
	return file_libs_proto_validator_proto_rawDescGZIP(), []int{1}
}

type NetworkType int32

const (
	NetworkType_NETWORK_TYPE_UNSPECIFIED NetworkType = 0
	NetworkType_MAINNET                  NetworkType = 1
	NetworkType_TESTNET                  NetworkType = 2
	NetworkType_DEVNET                   NetworkType = 3
	NetworkType_REGNET                   NetworkType = 4
)

// Enum value maps for NetworkType.
var (
	NetworkType_name = map[int32]string{
		0: "NETWORK_TYPE_UNSPECIFIED",
		1: "MAINNET",
		2: "TESTNET",
		3: "DEVNET",
		4: "REGNET",
	}
	NetworkType_value = map[string]int32{
		"NETWORK_TYPE_UNSPECIFIED": 0,
		"MAINNET":                  1,
		"TESTNET":                  2,
		"DEVNET":                   3,
		"REGNET":                   4,
	}
)

func (x NetworkType) Enum() *NetworkType {
	p := new(NetworkType)
	*p = x
	return p
}

func (x NetworkType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkType) Descriptor() protoreflect.EnumDescriptor {
	return file_libs_proto_validator_proto_enumTypes[2].Descriptor()
}

func (NetworkType) Type() protoreflect.EnumType {
	return &file_libs_proto_validator_proto_enumTypes[2]
}

func (x NetworkType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkType.Descriptor instead.
func (NetworkType) EnumDescriptor() ([]byte, []int) {
	return file_libs_proto_validator_proto_rawDescGZIP(), []int{2}
}

type OperationType int32

const (
	OperationType_OPERATION_TYPE_UNSPECIFIED OperationType = 0
	OperationType_TRANSACTION                OperationType = 1
	OperationType_SEND_TO_BRIDGE             OperationType = 2
	OperationType_SOLVER                     OperationType = 3
	OperationType_BRIDGE_DEPOSIT             OperationType = 4
	OperationType_SWAP                       OperationType = 5
	OperationType_BURN                       OperationType = 6
	OperationType_WITHDRAW                   OperationType = 7
	OperationType_BURN_SYNTHETIC             OperationType = 8
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0: "OPERATION_TYPE_UNSPECIFIED",
		1: "TRANSACTION",
		2: "SEND_TO_BRIDGE",
		3: "SOLVER",
		4: "BRIDGE_DEPOSIT",
		5: "SWAP",
		6: "BURN",
		7: "WITHDRAW",
		8: "BURN_SYNTHETIC",
	}
	OperationType_value = map[string]int32{
		"OPERATION_TYPE_UNSPECIFIED": 0,
		"TRANSACTION":                1,
		"SEND_TO_BRIDGE":             2,
		"SOLVER":                     3,
		"BRIDGE_DEPOSIT":             4,
		"SWAP":                       5,
		"BURN":                       6,
		"WITHDRAW":                   7,
		"BURN_SYNTHETIC":             8,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_libs_proto_validator_proto_enumTypes[3].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_libs_proto_validator_proto_enumTypes[3]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationType.Descriptor instead.
func (OperationType) EnumDescriptor() ([]byte, []int) {
	return file_libs_proto_validator_proto_rawDescGZIP(), []int{3}
}

type IntentStatus int32

const (
	IntentStatus_INTENT_STATUS_UNSPECIFIED IntentStatus = 0
	IntentStatus_INTENT_STATUS_PROCESSING  IntentStatus = 1
	IntentStatus_INTENT_STATUS_COMPLETED   IntentStatus = 2
	IntentStatus_INTENT_STATUS_FAILED      IntentStatus = 3
	IntentStatus_INTENT_STATUS_EXPIRED     IntentStatus = 4
)

// Enum value maps for IntentStatus.
var (
	IntentStatus_name = map[int32]string{
		0: "INTENT_STATUS_UNSPECIFIED",
		1: "INTENT_STATUS_PROCESSING",
		2: "INTENT_STATUS_COMPLETED",
		3: "INTENT_STATUS_FAILED",
		4: "INTENT_STATUS_EXPIRED",
	}
	IntentStatus_value = map[string]int32{
		"INTENT_STATUS_UNSPECIFIED": 0,
		"INTENT_STATUS_PROCESSING":  1,
		"INTENT_STATUS_COMPLETED":   2,
		"INTENT_STATUS_FAILED":      3,
		"INTENT_STATUS_EXPIRED":     4,
	}
)

func (x IntentStatus) Enum() *IntentStatus {
	p := new(IntentStatus)
	*p = x
	return p
}

func (x IntentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IntentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_libs_proto_validator_proto_enumTypes[4].Descriptor()
}

func (IntentStatus) Type() protoreflect.EnumType {
	return &file_libs_proto_validator_proto_enumTypes[4]
}

func (x IntentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IntentStatus.Descriptor instead.
func (IntentStatus) EnumDescriptor() ([]byte, []int) {
	return file_libs_proto_validator_proto_rawDescGZIP(), []int{4}
}

type OperationStatus int32

const (
	OperationStatus_OPERATION_STATUS_UNSPECIFIED OperationStatus = 0
	OperationStatus_OPERATION_STATUS_PENDING     OperationStatus = 1
	OperationStatus_OPERATION_STATUS_WAITING     OperationStatus = 2
	OperationStatus_OPERATION_STATUS_COMPLETED   OperationStatus = 3
	OperationStatus_OPERATION_STATUS_FAILED      OperationStatus = 4
	OperationStatus_OPERATION_STATUS_EXPIRED     OperationStatus = 5
)

// Enum value maps for OperationStatus.
var (
	OperationStatus_name = map[int32]string{
		0: "OPERATION_STATUS_UNSPECIFIED",
		1: "OPERATION_STATUS_PENDING",
		2: "OPERATION_STATUS_WAITING",
		3: "OPERATION_STATUS_COMPLETED",
		4: "OPERATION_STATUS_FAILED",
		5: "OPERATION_STATUS_EXPIRED",
	}
	OperationStatus_value = map[string]int32{
		"OPERATION_STATUS_UNSPECIFIED": 0,
		"OPERATION_STATUS_PENDING":     1,
		"OPERATION_STATUS_WAITING":     2,
		"OPERATION_STATUS_COMPLETED":   3,
		"OPERATION_STATUS_FAILED":      4,
		"OPERATION_STATUS_EXPIRED":     5,
	}
)

func (x OperationStatus) Enum() *OperationStatus {
	p := new(OperationStatus)
	*p = x
	return p
}

func (x OperationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_libs_proto_validator_proto_enumTypes[5].Descriptor()
}

func (OperationStatus) Type() protoreflect.EnumType {
	return &file_libs_proto_validator_proto_enumTypes[5]
}

func (x OperationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationStatus.Descriptor instead.
func (OperationStatus) EnumDescriptor() ([]byte, []int) {
	return file_libs_proto_validator_proto_rawDescGZIP(), []int{5}
}

type Operation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Type          OperationType          `protobuf:"varint,2,opt,name=type,proto3,enum=validator.OperationType" json:"type,omitempty"`
	BlockchainId  BlockchainID           `protobuf:"varint,3,opt,name=blockchain_id,json=blockchainId,proto3,enum=validator.BlockchainID" json:"blockchain_id,omitempty"`
	NetworkType   NetworkType            `protobuf:"varint,4,opt,name=network_type,json=networkType,proto3,enum=validator.NetworkType" json:"network_type,omitempty"`
	Result        string                 `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	SerializedTxn string                 `protobuf:"bytes,6,opt,name=serialized_txn,json=serializedTxn,proto3" json:"serialized_txn,omitempty"`
	Solver        *Solver                `protobuf:"bytes,7,opt,name=solver,proto3" json:"solver,omitempty"`
	DataToSign    *string                `protobuf:"bytes,8,opt,name=data_to_sign,json=dataToSign,proto3,oneof" json:"data_to_sign,omitempty"`
	Status        OperationStatus        `protobuf:"varint,9,opt,name=status,proto3,enum=validator.OperationStatus" json:"status,omitempty"`
	GenesisHash   string                 `protobuf:"bytes,10,opt,name=genesis_hash,json=genesisHash,proto3" json:"genesis_hash,omitempty"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_libs_proto_validator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_libs_proto_validator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_libs_proto_validator_proto_rawDescGZIP(), []int{0}
}

func (x *Operation) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Operation) GetType() OperationType {
	if x != nil {
		return x.Type
	}
	return OperationType_OPERATION_TYPE_UNSPECIFIED
}

func (x *Operation) GetBlockchainId() BlockchainID {
	if x != nil {
		return x.BlockchainId
	}
	return BlockchainID_BLOCKCHAIN_ID_UNSPECIFIED
}

func (x *Operation) GetNetworkType() NetworkType {
	if x != nil {
		return x.NetworkType
	}
	return NetworkType_NETWORK_TYPE_UNSPECIFIED
}

func (x *Operation) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *Operation) GetSerializedTxn() string {
	if x != nil {
		return x.SerializedTxn
	}
	return ""
}

func (x *Operation) GetSolver() *Solver {
	if x != nil {
		return x.Solver
	}
	return nil
}

func (x *Operation) GetDataToSign() string {
	if x != nil && x.DataToSign != nil {
		return *x.DataToSign
	}
	return ""
}

func (x *Operation) GetStatus() OperationStatus {
	if x != nil {
		return x.Status
	}
	return OperationStatus_OPERATION_STATUS_UNSPECIFIED
}

func (x *Operation) GetGenesisHash() string {
	if x != nil {
		return x.GenesisHash
	}
	return ""
}

func (x *Operation) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Solver struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Metadata      string                 `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	DataToSign    string                 `protobuf:"bytes,3,opt,name=data_to_sign,json=dataToSign,proto3" json:"data_to_sign,omitempty"`
	Output        string                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Solver) Reset() {
	*x = Solver{}
	mi := &file_libs_proto_validator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Solver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Solver) ProtoMessage() {}

func (x *Solver) ProtoReflect() protoreflect.Message {
	mi := &file_libs_proto_validator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Solver.ProtoReflect.Descriptor instead.
func (*Solver) Descriptor() ([]byte, []int) {
	return file_libs_proto_validator_proto_rawDescGZIP(), []int{1}
}

func (x *Solver) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Solver) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *Solver) GetDataToSign() string {
	if x != nil {
		return x.DataToSign
	}
	return ""
}

func (x *Solver) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type Intent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Identity      string                 `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	BlockchainId  BlockchainID           `protobuf:"varint,3,opt,name=blockchain_id,json=blockchainId,proto3,enum=validator.BlockchainID" json:"blockchain_id,omitempty"`
	NetworkType   NetworkType            `protobuf:"varint,4,opt,name=network_type,json=networkType,proto3,enum=validator.NetworkType" json:"network_type,omitempty"`
	Operations    []*Operation           `protobuf:"bytes,5,rep,name=operations,proto3" json:"operations,omitempty"`
	Expiry        *timestamp.Timestamp   `protobuf:"bytes,6,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Signature     string                 `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	Status        IntentStatus           `protobuf:"varint,8,opt,name=status,proto3,enum=validator.IntentStatus" json:"status,omitempty"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Intent) Reset() {
	*x = Intent{}
	mi := &file_libs_proto_validator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Intent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Intent) ProtoMessage() {}

func (x *Intent) ProtoReflect() protoreflect.Message {
	mi := &file_libs_proto_validator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Intent.ProtoReflect.Descriptor instead.
func (*Intent) Descriptor() ([]byte, []int) {
	return file_libs_proto_validator_proto_rawDescGZIP(), []int{2}
}

func (x *Intent) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Intent) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *Intent) GetBlockchainId() BlockchainID {
	if x != nil {
		return x.BlockchainId
	}
	return BlockchainID_BLOCKCHAIN_ID_UNSPECIFIED
}

func (x *Intent) GetNetworkType() NetworkType {
	if x != nil {
		return x.NetworkType
	}
	return NetworkType_NETWORK_TYPE_UNSPECIFIED
}

func (x *Intent) GetOperations() []*Operation {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *Intent) GetExpiry() *timestamp.Timestamp {
	if x != nil {
		return x.Expiry
	}
	return nil
}

func (x *Intent) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *Intent) GetStatus() IntentStatus {
	if x != nil {
		return x.Status
	}
	return IntentStatus_INTENT_STATUS_UNSPECIFIED
}

func (x *Intent) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Keygen (/keygen) - Mirrors CreateWallet struct
type KeygenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	IdentityCurve Curve                  `protobuf:"varint,2,opt,name=identity_curve,json=identityCurve,proto3,enum=validator.Curve" json:"identity_curve,omitempty"`
	Signers       []string               `protobuf:"bytes,3,rep,name=signers,proto3" json:"signers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeygenRequest) Reset() {
	*x = KeygenRequest{}
	mi := &file_libs_proto_validator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeygenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeygenRequest) ProtoMessage() {}

func (x *KeygenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libs_proto_validator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeygenRequest.ProtoReflect.Descriptor instead.
func (*KeygenRequest) Descriptor() ([]byte, []int) {
	return file_libs_proto_validator_proto_rawDescGZIP(), []int{3}
}

func (x *KeygenRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *KeygenRequest) GetIdentityCurve() Curve {
	if x != nil {
		return x.IdentityCurve
	}
	return Curve_CURVE_UNSPECIFIED
}

func (x *KeygenRequest) GetSigners() []string {
	if x != nil {
		return x.Signers
	}
	return nil
}

type KeygenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // e.g., "Keygen operation completed successfully" or error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeygenResponse) Reset() {
	*x = KeygenResponse{}
	mi := &file_libs_proto_validator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeygenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeygenResponse) ProtoMessage() {}

func (x *KeygenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libs_proto_validator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeygenResponse.ProtoReflect.Descriptor instead.
func (*KeygenResponse) Descriptor() ([]byte, []int) {
	return file_libs_proto_validator_proto_rawDescGZIP(), []int{4}
}

func (x *KeygenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetAddresses (/address)
type GetAddressesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	IdentityCurve Curve                  `protobuf:"varint,2,opt,name=identity_curve,json=identityCurve,proto3,enum=validator.Curve" json:"identity_curve,omitempty"` // Changed from string query param
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressesRequest) Reset() {
	*x = GetAddressesRequest{}
	mi := &file_libs_proto_validator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressesRequest) ProtoMessage() {}

func (x *GetAddressesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libs_proto_validator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressesRequest.ProtoReflect.Descriptor instead.
func (*GetAddressesRequest) Descriptor() ([]byte, []int) {
	return file_libs_proto_validator_proto_rawDescGZIP(), []int{5}
}

func (x *GetAddressesRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *GetAddressesRequest) GetIdentityCurve() Curve {
	if x != nil {
		return x.IdentityCurve
	}
	return Curve_CURVE_UNSPECIFIED
}

type AddressDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkType   NetworkType            `protobuf:"varint,1,opt,name=network_type,json=networkType,proto3,enum=validator.NetworkType" json:"network_type,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressDetail) Reset() {
	*x = AddressDetail{}
	mi := &file_libs_proto_validator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressDetail) ProtoMessage() {}

func (x *AddressDetail) ProtoReflect() protoreflect.Message {
	mi := &file_libs_proto_validator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressDetail.ProtoReflect.Descriptor instead.
func (*AddressDetail) Descriptor() ([]byte, []int) {
	return file_libs_proto_validator_proto_rawDescGZIP(), []int{6}
}

func (x *AddressDetail) GetNetworkType() NetworkType {
	if x != nil {
		return x.NetworkType
	}
	return NetworkType_NETWORK_TYPE_UNSPECIFIED
}

func (x *AddressDetail) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// Using nested maps to represent map[BlockchainID]map[NetworkType]string
type BlockchainAddressMap struct {
	state            protoimpl.MessageState   `protogen:"open.v1"`
	NetworkAddresses map[int32]*AddressDetail `protobuf:"bytes,1,rep,name=network_addresses,json=networkAddresses,proto3" json:"network_addresses,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BlockchainAddressMap) Reset() {
	*x = BlockchainAddressMap{}
	mi := &file_libs_proto_validator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockchainAddressMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockchainAddressMap) ProtoMessage() {}

func (x *BlockchainAddressMap) ProtoReflect() protoreflect.Message {
	mi := &file_libs_proto_validator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockchainAddressMap.ProtoReflect.Descriptor instead.
func (*BlockchainAddressMap) Descriptor() ([]byte, []int) {
	return file_libs_proto_validator_proto_rawDescGZIP(), []int{7}
}

func (x *BlockchainAddressMap) GetNetworkAddresses() map[int32]*AddressDetail {
	if x != nil {
		return x.NetworkAddresses
	}
	return nil
}

type GetAddressesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Key is BlockchainID enum value
	Addresses     map[int32]*BlockchainAddressMap `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	EddsaAddress  string                          `protobuf:"bytes,2,opt,name=eddsa_address,json=eddsaAddress,proto3" json:"eddsa_address,omitempty"`
	EcdsaAddress  string                          `protobuf:"bytes,3,opt,name=ecdsa_address,json=ecdsaAddress,proto3" json:"ecdsa_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressesResponse) Reset() {
	*x = GetAddressesResponse{}
	mi := &file_libs_proto_validator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressesResponse) ProtoMessage() {}

func (x *GetAddressesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libs_proto_validator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressesResponse.ProtoReflect.Descriptor instead.
func (*GetAddressesResponse) Descriptor() ([]byte, []int) {
	return file_libs_proto_validator_proto_rawDescGZIP(), []int{8}
}

func (x *GetAddressesResponse) GetAddresses() map[int32]*BlockchainAddressMap {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *GetAddressesResponse) GetEddsaAddress() string {
	if x != nil {
		return x.EddsaAddress
	}
	return ""
}

func (x *GetAddressesResponse) GetEcdsaAddress() string {
	if x != nil {
		return x.EcdsaAddress
	}
	return ""
}

// SignIntentOperation (/signature)
type SignIntentOperationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Intent         *Intent                `protobuf:"bytes,1,opt,name=intent,proto3" json:"intent,omitempty"`                                        // Pass the whole intent object
	OperationIndex uint32                 `protobuf:"varint,2,opt,name=operation_index,json=operationIndex,proto3" json:"operation_index,omitempty"` // From query param
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SignIntentOperationRequest) Reset() {
	*x = SignIntentOperationRequest{}
	mi := &file_libs_proto_validator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignIntentOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignIntentOperationRequest) ProtoMessage() {}

func (x *SignIntentOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libs_proto_validator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignIntentOperationRequest.ProtoReflect.Descriptor instead.
func (*SignIntentOperationRequest) Descriptor() ([]byte, []int) {
	return file_libs_proto_validator_proto_rawDescGZIP(), []int{9}
}

func (x *SignIntentOperationRequest) GetIntent() *Intent {
	if x != nil {
		return x.Intent
	}
	return nil
}

func (x *SignIntentOperationRequest) GetOperationIndex() uint32 {
	if x != nil {
		return x.OperationIndex
	}
	return 0
}

// Mirrors SignatureResponse struct
type SignIntentOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     string                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignIntentOperationResponse) Reset() {
	*x = SignIntentOperationResponse{}
	mi := &file_libs_proto_validator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignIntentOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignIntentOperationResponse) ProtoMessage() {}

func (x *SignIntentOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libs_proto_validator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignIntentOperationResponse.ProtoReflect.Descriptor instead.
func (*SignIntentOperationResponse) Descriptor() ([]byte, []int) {
	return file_libs_proto_validator_proto_rawDescGZIP(), []int{10}
}

func (x *SignIntentOperationResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

var File_libs_proto_validator_proto protoreflect.FileDescriptor

const file_libs_proto_validator_proto_rawDesc = "" +
	"\n" +
	"\x1alibs/proto/validator.proto\x12\tvalidator\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf6\x03\n" +
	"\tOperation\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12,\n" +
	"\x04type\x18\x02 \x01(\x0e2\x18.validator.OperationTypeR\x04type\x12<\n" +
	"\rblockchain_id\x18\x03 \x01(\x0e2\x17.validator.BlockchainIDR\fblockchainId\x129\n" +
	"\fnetwork_type\x18\x04 \x01(\x0e2\x16.validator.NetworkTypeR\vnetworkType\x12\x16\n" +
	"\x06result\x18\x05 \x01(\tR\x06result\x12%\n" +
	"\x0eserialized_txn\x18\x06 \x01(\tR\rserializedTxn\x12)\n" +
	"\x06solver\x18\a \x01(\v2\x11.validator.SolverR\x06solver\x12%\n" +
	"\fdata_to_sign\x18\b \x01(\tH\x00R\n" +
	"dataToSign\x88\x01\x01\x122\n" +
	"\x06status\x18\t \x01(\x0e2\x1a.validator.OperationStatusR\x06status\x12!\n" +
	"\fgenesis_hash\x18\n" +
	" \x01(\tR\vgenesisHash\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x0f\n" +
	"\r_data_to_sign\"v\n" +
	"\x06Solver\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x1a\n" +
	"\bmetadata\x18\x02 \x01(\tR\bmetadata\x12 \n" +
	"\fdata_to_sign\x18\x03 \x01(\tR\n" +
	"dataToSign\x12\x16\n" +
	"\x06output\x18\x04 \x01(\tR\x06output\"\xa1\x03\n" +
	"\x06Intent\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x1a\n" +
	"\bidentity\x18\x02 \x01(\tR\bidentity\x12<\n" +
	"\rblockchain_id\x18\x03 \x01(\x0e2\x17.validator.BlockchainIDR\fblockchainId\x129\n" +
	"\fnetwork_type\x18\x04 \x01(\x0e2\x16.validator.NetworkTypeR\vnetworkType\x124\n" +
	"\n" +
	"operations\x18\x05 \x03(\v2\x14.validator.OperationR\n" +
	"operations\x122\n" +
	"\x06expiry\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x06expiry\x12\x1c\n" +
	"\tsignature\x18\a \x01(\tR\tsignature\x12/\n" +
	"\x06status\x18\b \x01(\x0e2\x17.validator.IntentStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"~\n" +
	"\rKeygenRequest\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x127\n" +
	"\x0eidentity_curve\x18\x02 \x01(\x0e2\x10.validator.CurveR\ridentityCurve\x12\x18\n" +
	"\asigners\x18\x03 \x03(\tR\asigners\"*\n" +
	"\x0eKeygenResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"j\n" +
	"\x13GetAddressesRequest\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x127\n" +
	"\x0eidentity_curve\x18\x02 \x01(\x0e2\x10.validator.CurveR\ridentityCurve\"d\n" +
	"\rAddressDetail\x129\n" +
	"\fnetwork_type\x18\x01 \x01(\x0e2\x16.validator.NetworkTypeR\vnetworkType\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"\xd9\x01\n" +
	"\x14BlockchainAddressMap\x12b\n" +
	"\x11network_addresses\x18\x01 \x03(\v25.validator.BlockchainAddressMap.NetworkAddressesEntryR\x10networkAddresses\x1a]\n" +
	"\x15NetworkAddressesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.validator.AddressDetailR\x05value:\x028\x01\"\x8d\x02\n" +
	"\x14GetAddressesResponse\x12L\n" +
	"\taddresses\x18\x01 \x03(\v2..validator.GetAddressesResponse.AddressesEntryR\taddresses\x12#\n" +
	"\reddsa_address\x18\x02 \x01(\tR\feddsaAddress\x12#\n" +
	"\recdsa_address\x18\x03 \x01(\tR\fecdsaAddress\x1a]\n" +
	"\x0eAddressesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.validator.BlockchainAddressMapR\x05value:\x028\x01\"p\n" +
	"\x1aSignIntentOperationRequest\x12)\n" +
	"\x06intent\x18\x01 \x01(\v2\x11.validator.IntentR\x06intent\x12'\n" +
	"\x0foperation_index\x18\x02 \x01(\rR\x0eoperationIndex\";\n" +
	"\x1bSignIntentOperationResponse\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\tR\tsignature*@\n" +
	"\x05Curve\x12\x15\n" +
	"\x11CURVE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vCURVE_ECDSA\x10\x01\x12\x0f\n" +
	"\vCURVE_EDDSA\x10\x02*\xe2\x01\n" +
	"\fBlockchainID\x12\x1d\n" +
	"\x19BLOCKCHAIN_ID_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aBITCOIN\x10\x01\x12\f\n" +
	"\bETHEREUM\x10\x02\x12\n" +
	"\n" +
	"\x06SOLANA\x10\x03\x12\f\n" +
	"\bDOGECOIN\x10\x04\x12\a\n" +
	"\x03SUI\x10\x05\x12\t\n" +
	"\x05APTOS\x10\x06\x12\v\n" +
	"\aSTELLAR\x10\a\x12\f\n" +
	"\bALGORAND\x10\b\x12\n" +
	"\n" +
	"\x06RIPPLE\x10\t\x12\v\n" +
	"\aCARDANO\x10\n" +
	"\x12\x0e\n" +
	"\n" +
	"STRIPCHAIN\x10\v\x12\f\n" +
	"\bARBITRUM\x10\f\x12\t\n" +
	"\x05SONIC\x10\r\x12\r\n" +
	"\tBERACHAIN\x10\x0e*]\n" +
	"\vNetworkType\x12\x1c\n" +
	"\x18NETWORK_TYPE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aMAINNET\x10\x01\x12\v\n" +
	"\aTESTNET\x10\x02\x12\n" +
	"\n" +
	"\x06DEVNET\x10\x03\x12\n" +
	"\n" +
	"\x06REGNET\x10\x04*\xaa\x01\n" +
	"\rOperationType\x12\x1e\n" +
	"\x1aOPERATION_TYPE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vTRANSACTION\x10\x01\x12\x12\n" +
	"\x0eSEND_TO_BRIDGE\x10\x02\x12\n" +
	"\n" +
	"\x06SOLVER\x10\x03\x12\x12\n" +
	"\x0eBRIDGE_DEPOSIT\x10\x04\x12\b\n" +
	"\x04SWAP\x10\x05\x12\b\n" +
	"\x04BURN\x10\x06\x12\f\n" +
	"\bWITHDRAW\x10\a\x12\x12\n" +
	"\x0eBURN_SYNTHETIC\x10\b*\x9d\x01\n" +
	"\fIntentStatus\x12\x1d\n" +
	"\x19INTENT_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18INTENT_STATUS_PROCESSING\x10\x01\x12\x1b\n" +
	"\x17INTENT_STATUS_COMPLETED\x10\x02\x12\x18\n" +
	"\x14INTENT_STATUS_FAILED\x10\x03\x12\x19\n" +
	"\x15INTENT_STATUS_EXPIRED\x10\x04*\xca\x01\n" +
	"\x0fOperationStatus\x12 \n" +
	"\x1cOPERATION_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18OPERATION_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18OPERATION_STATUS_WAITING\x10\x02\x12\x1e\n" +
	"\x1aOPERATION_STATUS_COMPLETED\x10\x03\x12\x1b\n" +
	"\x17OPERATION_STATUS_FAILED\x10\x04\x12\x1c\n" +
	"\x18OPERATION_STATUS_EXPIRED\x10\x052\x88\x02\n" +
	"\x10ValidatorService\x12=\n" +
	"\x06Keygen\x12\x18.validator.KeygenRequest\x1a\x19.validator.KeygenResponse\x12O\n" +
	"\fGetAddresses\x12\x1e.validator.GetAddressesRequest\x1a\x1f.validator.GetAddressesResponse\x12d\n" +
	"\x13SignIntentOperation\x12%.validator.SignIntentOperationRequest\x1a&.validator.SignIntentOperationResponseB\x0eZ\f./;validatorb\x06proto3"

var (
	file_libs_proto_validator_proto_rawDescOnce sync.Once
	file_libs_proto_validator_proto_rawDescData []byte
)

func file_libs_proto_validator_proto_rawDescGZIP() []byte {
	file_libs_proto_validator_proto_rawDescOnce.Do(func() {
		file_libs_proto_validator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_libs_proto_validator_proto_rawDesc), len(file_libs_proto_validator_proto_rawDesc)))
	})
	return file_libs_proto_validator_proto_rawDescData
}

var file_libs_proto_validator_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_libs_proto_validator_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_libs_proto_validator_proto_goTypes = []any{
	(Curve)(0),                          // 0: validator.Curve
	(BlockchainID)(0),                   // 1: validator.BlockchainID
	(NetworkType)(0),                    // 2: validator.NetworkType
	(OperationType)(0),                  // 3: validator.OperationType
	(IntentStatus)(0),                   // 4: validator.IntentStatus
	(OperationStatus)(0),                // 5: validator.OperationStatus
	(*Operation)(nil),                   // 6: validator.Operation
	(*Solver)(nil),                      // 7: validator.Solver
	(*Intent)(nil),                      // 8: validator.Intent
	(*KeygenRequest)(nil),               // 9: validator.KeygenRequest
	(*KeygenResponse)(nil),              // 10: validator.KeygenResponse
	(*GetAddressesRequest)(nil),         // 11: validator.GetAddressesRequest
	(*AddressDetail)(nil),               // 12: validator.AddressDetail
	(*BlockchainAddressMap)(nil),        // 13: validator.BlockchainAddressMap
	(*GetAddressesResponse)(nil),        // 14: validator.GetAddressesResponse
	(*SignIntentOperationRequest)(nil),  // 15: validator.SignIntentOperationRequest
	(*SignIntentOperationResponse)(nil), // 16: validator.SignIntentOperationResponse
	nil,                                 // 17: validator.BlockchainAddressMap.NetworkAddressesEntry
	nil,                                 // 18: validator.GetAddressesResponse.AddressesEntry
	(*timestamp.Timestamp)(nil),         // 19: google.protobuf.Timestamp
}
var file_libs_proto_validator_proto_depIdxs = []int32{
	3,  // 0: validator.Operation.type:type_name -> validator.OperationType
	1,  // 1: validator.Operation.blockchain_id:type_name -> validator.BlockchainID
	2,  // 2: validator.Operation.network_type:type_name -> validator.NetworkType
	7,  // 3: validator.Operation.solver:type_name -> validator.Solver
	5,  // 4: validator.Operation.status:type_name -> validator.OperationStatus
	19, // 5: validator.Operation.created_at:type_name -> google.protobuf.Timestamp
	1,  // 6: validator.Intent.blockchain_id:type_name -> validator.BlockchainID
	2,  // 7: validator.Intent.network_type:type_name -> validator.NetworkType
	6,  // 8: validator.Intent.operations:type_name -> validator.Operation
	19, // 9: validator.Intent.expiry:type_name -> google.protobuf.Timestamp
	4,  // 10: validator.Intent.status:type_name -> validator.IntentStatus
	19, // 11: validator.Intent.created_at:type_name -> google.protobuf.Timestamp
	0,  // 12: validator.KeygenRequest.identity_curve:type_name -> validator.Curve
	0,  // 13: validator.GetAddressesRequest.identity_curve:type_name -> validator.Curve
	2,  // 14: validator.AddressDetail.network_type:type_name -> validator.NetworkType
	17, // 15: validator.BlockchainAddressMap.network_addresses:type_name -> validator.BlockchainAddressMap.NetworkAddressesEntry
	18, // 16: validator.GetAddressesResponse.addresses:type_name -> validator.GetAddressesResponse.AddressesEntry
	8,  // 17: validator.SignIntentOperationRequest.intent:type_name -> validator.Intent
	12, // 18: validator.BlockchainAddressMap.NetworkAddressesEntry.value:type_name -> validator.AddressDetail
	13, // 19: validator.GetAddressesResponse.AddressesEntry.value:type_name -> validator.BlockchainAddressMap
	9,  // 20: validator.ValidatorService.Keygen:input_type -> validator.KeygenRequest
	11, // 21: validator.ValidatorService.GetAddresses:input_type -> validator.GetAddressesRequest
	15, // 22: validator.ValidatorService.SignIntentOperation:input_type -> validator.SignIntentOperationRequest
	10, // 23: validator.ValidatorService.Keygen:output_type -> validator.KeygenResponse
	14, // 24: validator.ValidatorService.GetAddresses:output_type -> validator.GetAddressesResponse
	16, // 25: validator.ValidatorService.SignIntentOperation:output_type -> validator.SignIntentOperationResponse
	23, // [23:26] is the sub-list for method output_type
	20, // [20:23] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_libs_proto_validator_proto_init() }
func file_libs_proto_validator_proto_init() {
	if File_libs_proto_validator_proto != nil {
		return
	}
	file_libs_proto_validator_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_libs_proto_validator_proto_rawDesc), len(file_libs_proto_validator_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_libs_proto_validator_proto_goTypes,
		DependencyIndexes: file_libs_proto_validator_proto_depIdxs,
		EnumInfos:         file_libs_proto_validator_proto_enumTypes,
		MessageInfos:      file_libs_proto_validator_proto_msgTypes,
	}.Build()
	File_libs_proto_validator_proto = out.File
	file_libs_proto_validator_proto_goTypes = nil
	file_libs_proto_validator_proto_depIdxs = nil
}
