apiVersion: v1
kind: Service
metadata:
  name: backend-strip-node-sequencer
  namespace: dev
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http
    - port: 30306
      targetPort: 30306
      name: p2p
  selector:
    app: backend-strip-node-sequencer 