apiVersion: v1
kind: Service
metadata:
  name: sequencer
  namespace: dev
spec:
  ports:
    - port: 80
      targetPort: 8082
      name: http
    - port: 30306
      targetPort: 30306
      name: p2p
  selector:
    app: sequencer 