apiVersion: v1
kind: Service
metadata:
  name: backend-strip-node-solver
spec:
  selector:
    app: backend-strip-node-solver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP 