apiVersion: v1
kind: Service
metadata:
  name: backend-strip-node-validator1
  namespace: dev
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http
      protocol: TCP
    - port: 30304
      targetPort: 30304
      name: p2p
  selector:
    app: backend-strip-node-validator1