apiVersion: v1
kind: Service
metadata:
  name: validator2
  namespace: dev
spec:
  ports:
    - port: 8081
      targetPort: 8081
      name: http
    - port: 30305
      targetPort: 30305
      name: p2p
  selector:
    app: validator2 