name: Strip Node CI/CD for Validators

on:
  push:
    branches:
      - main
      - stage
      - develop
  pull_request:
    branches:
      - develop
      - stage
      - main

env:
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  IMAGE_TAG: ${{ github.sha }}  

jobs:
  build-and-test:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
     
      - name: Update CA certificates
        run: sudo apt-get update && sudo apt-get install -y ca-certificates

      - name: Configure Git to skip SSL verification
        run: git config --global http.sslVerify false

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            REPOSITORY_PREFIX="prod"
          elif [[ "${{ github.ref }}" == "refs/heads/stage" ]]; then
            REPOSITORY_PREFIX="stage"
          else
            REPOSITORY_PREFIX="dev"
          fi
      
          COMPONENT_TYPE=backend
          COMPONENT_REPO=strip-node
          COMPONENT_NAME=validator
      
          IMAGE_TAG_FORMAT="$ECR_REGISTRY/$REPOSITORY_PREFIX/$COMPONENT_TYPE/$COMPONENT_REPO/$COMPONENT_NAME"
      
          echo "Building Docker image with tag: $IMAGE_TAG_FORMAT:${{ env.IMAGE_TAG }}"
      
          docker build -t $IMAGE_TAG_FORMAT:${{ env.IMAGE_TAG }} -t $IMAGE_TAG_FORMAT:latest .
          docker push $IMAGE_TAG_FORMAT:${{ env.IMAGE_TAG }}
          docker push $IMAGE_TAG_FORMAT:latest
      - name: Deploy using Kustomize
        run: |
          aws eks update-kubeconfig --name stripchain --region ${{ env.AWS_REGION }}
          
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            NAMESPACE="prod"
          elif [[ "${{ github.ref }}" == "refs/heads/stage" ]]; then
            NAMESPACE="stage"
          else
            NAMESPACE="dev"
          fi
          
          COMPONENT_TYPE=backend
          COMPONENT_REPO=strip-node
          
          # Get all validator deployments and restart them
          kubectl get deployments -n ${NAMESPACE} | grep "${COMPONENT_TYPE}-${COMPONENT_REPO}-validator" | awk '{print $1}' | xargs -I{} kubectl rollout restart deployment {} -n ${NAMESPACE}
          
          echo "All validator deployments in ${NAMESPACE} namespace have been restarted"
